### PR TITLE
feat: generalize select_n dispatch

### PR DESCRIPTION
**Pull request by nstarman**
Now the dispatch uses a non-Q selector for a set of Q cases.

Addresses problem identified in private communication.

### CODE REVIEW

**Review by adrn — APPROVED** [review]
Nice! The example in the docs will get run as a doctest, right? So don't need to add a separate unit test?

**Comment by nstarman** [comment]
> The example in the docs will get run as a doctest, right? So don't need to add a separate unit test?

Yes!

**Comment by nstarman** [comment]
@adrn do you need a bugfix release?

**Comment by adrn** [comment]
Not urgently

**Pull request merged**
