### PR TITLE
feat: complete rewrite of the docs

### PR DESCRIPTION
**Pull request by nstarman**

### CODE REVIEW

**Comment by nstarman** [comment]
I think it's ready!
Happy to change stuff.
If there's new sections let's do this in a followup PR :).

**Review by adrn — COMMENTED** [review]
This is in great shape! I opened a PR with some suggested edits.

**Comment by nstarman** [comment]
The PR looks good, but it's failing CI.

**Review by adrn — APPROVED** [review]
LGTM now!

**Comment by nstarman** [comment]
Rebasing to fix file conflict. Then merging 🎉

**Pull request merged**
